# Generated by Django 3.2.15 on 2022-11-02 14:51

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomep', models.CharField(max_length=100)),
                ('matricula', models.DecimalField(decimal_places=0, max_digits=10)),
                ('curso', models.CharField(choices=[['Automação Industrial', 'Automação Industrial'], ['Engenharia de Software', 'Engenharia de Software'], ['Engenharia Elétrica', 'Engenharia Elétrica'], ['Engenharia Mecânica', 'Engenharia Mecânica']], max_length=100)),
                ('periodo', models.CharField(choices=[['1°', '1°'], ['2°', '2°'], ['3°', '3°'], ['4°', '4°'], ['5°', '5°'], ['6°', '6°'], ['7°', '7°'], ['8°', '8°'], ['9°', '9°'], ['10°', '10°']], max_length=3)),
                ('turma', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=14)),
                ('CPF', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
            ],
            options={
                'verbose_name': 'Cadastro de Aluno',
                'verbose_name_plural': 'Cadastros de Alunos',
            },
        ),
        migrations.CreateModel(
            name='CadastroFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Cadastro de Funcionário',
                'verbose_name_plural': 'Cadastros de Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Emprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255, unique=True)),
                ('site', models.URLField()),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[['Estágio', 'Estágio'], ['Registrado', 'Registrado']], max_length=100)),
                ('periodo', models.CharField(choices=[['Comercial', 'Comercial'], ['Dia', 'Dia'], ['Integral', 'Integral'], ['Noite', 'Noite'], ['12H por 16H', '12H por 16H']], max_length=100)),
                ('area', models.CharField(choices=[['Automação', 'Automação'], ['Elétrica', 'Elétrica'], ['Mecânica', 'Mecânica'], ['TI', 'TI']], max_length=100)),
                ('descricao', models.TextField(blank=True, default='')),
                ('necessarios', models.TextField(default='')),
                ('desejaveis', models.TextField(default='')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Emprego',
                'verbose_name_plural': 'Empregos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[['Curso', 'Curso'], ['Evento Institucional', 'Evento Institucional'], ['Evento Não Institucional', 'Evento Não Institucional'], ['Jornada de Aprendizagem', 'Jornada de Aprendizagem'], ['Live', 'Live'], ['Mentoria', 'Mentoria'], ['Palestra', 'Palestra']], max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=285)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='eventos', variations={'thumb': (124, 124)}, verbose_name='imagem')),
                ('carga', models.IntegerField(blank=True, verbose_name='carga horaria')),
                ('descricao', models.TextField(blank=True, default='')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Cadastro de Evento',
                'verbose_name_plural': 'Cadastros de Eventos',
            },
        ),
        migrations.CreateModel(
            name='Sugestoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[['AVA', 'AVA'], ['Coordenação', 'Coordenação'], ['Estrutura', 'Estrutura'], ['Financeiro', 'Financeiro'], ['Geral', 'Geral'], ['Laboratórios', 'Laboratórios'], ['Pedagogia', 'Pedagogia'], ['Portal do Aluno', 'Portal do Aluno'], ['Secretária', 'Secretária']], max_length=100)),
                ('anonimo', models.BooleanField()),
                ('descricao', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
            },
        ),
    ]
